-- Executed SQL formula reference, generated from the production function.
WITH windowed AS (SELECT *,TIMESTAMPTZ '2019-12-01 00:00:00+00' t FROM int_behavior_events
    WHERE event_time>=TIMESTAMPTZ '2019-12-01 00:00:00+00'-INTERVAL '60 days' AND event_time<TIMESTAMPTZ '2019-12-01 00:00:00+00'),
    category_counts AS (SELECT user_id, category_id,count(*) n FROM windowed WHERE event_type='view' AND category_id IS NOT NULL GROUP BY 1,2),
    concentration AS (SELECT user_id,max(n)::DOUBLE/sum(n) category_view_concentration FROM category_counts GROUP BY 1),
    aggregates AS (SELECT user_id, t AS as_of_timestamp,
    epoch(t-max(event_time) FILTER(WHERE event_type='purchase'))/86400 purchase_recency,
    epoch(t-max(event_time))/86400 event_recency,
    epoch(t-max(event_time) FILTER(WHERE event_type='view'))/86400 view_recency,
    epoch(t-max(event_time) FILTER(WHERE event_type='cart'))/86400 cart_recency,
    count(DISTINCT event_time) FILTER(WHERE event_type='purchase') occasions_60,
    avg(valid_price::INTEGER) FILTER(WHERE event_type='purchase') valid_price_share,
    median(price) FILTER(WHERE event_type='purchase' AND valid_price) median_purchase_event_value,
    epoch(t-min(event_time) FILTER(WHERE event_type='purchase'))/86400 first_purchase_age,
    count(DISTINCT cast(event_time AS DATE)) FILTER(WHERE event_type='purchase')>1 repeat_buyer,
    epoch(max(event_time) FILTER(WHERE event_type='purchase')-min(event_time) FILTER(WHERE event_type='purchase'))/86400/nullif(count(DISTINCT event_time) FILTER(WHERE event_type='purchase')-1,0) mean_purchase_gap,
    count(DISTINCT user_session) FILTER(WHERE event_time>=t-INTERVAL '28 days') sessions_28,
    count(DISTINCT product_id) FILTER(WHERE event_type='view' AND event_time>=t-INTERVAL '28 days') products_28,
    count(DISTINCT category_id) FILTER(WHERE event_type='view' AND event_time>=t-INTERVAL '28 days') categories_28,
    count(*) FILTER(WHERE event_type='cart' AND event_time>=t-INTERVAL '14 days')>0 AND count(*) FILTER(WHERE event_type='purchase' AND event_time>=t-INTERVAL '14 days')=0 cart_without_purchase_14,
    count(*) FILTER(WHERE event_time>=t-INTERVAL '14 days') activity_recent_14,
    count(*) FILTER(WHERE event_time>=t-INTERVAL '28 days' AND event_time<t-INTERVAL '14 days') activity_previous_14,
    count(DISTINCT category_id) FILTER(WHERE event_type='purchase') purchase_categories,
    avg((user_session IS NULL)::INTEGER) missing_session_share,
    max(event_time) feature_max_timestamp, count(DISTINCT cast(event_time AS DATE)) FILTER(WHERE event_type='purchase' AND event_time>=t-INTERVAL '7 days') AS purchasing_days_7,
count(DISTINCT cast(event_time AS DATE)) FILTER(WHERE event_type='purchase' AND event_time>=t-INTERVAL '14 days') AS purchasing_days_14,
count(DISTINCT cast(event_time AS DATE)) FILTER(WHERE event_type='purchase' AND event_time>=t-INTERVAL '28 days') AS purchasing_days_28,
count(DISTINCT cast(event_time AS DATE)) FILTER(WHERE event_type='purchase' AND event_time>=t-INTERVAL '60 days') AS purchasing_days_60,
count(DISTINCT cast(event_time AS DATE)) FILTER(WHERE event_time>=t-INTERVAL '7 days') AS active_days_7,
count(DISTINCT cast(event_time AS DATE)) FILTER(WHERE event_time>=t-INTERVAL '14 days') AS active_days_14,
count(DISTINCT cast(event_time AS DATE)) FILTER(WHERE event_time>=t-INTERVAL '28 days') AS active_days_28,
count(*) FILTER(WHERE event_type='view' AND event_time>=t-INTERVAL '28 days') AS views_28,
count(*) FILTER(WHERE event_type='cart' AND event_time>=t-INTERVAL '28 days') AS carts_28,
count(*) FILTER(WHERE event_type='remove_from_cart' AND event_time>=t-INTERVAL '28 days') AS removals_28,
coalesce(sum(price) FILTER(WHERE event_type='purchase' AND valid_price AND event_time>=t-INTERVAL '28 days'),0) AS value_28,
coalesce(sum(price) FILTER(WHERE event_type='purchase' AND valid_price AND event_time>=t-INTERVAL '60 days'),0) AS value_60
    FROM windowed GROUP BY user_id,t HAVING count(*) FILTER(WHERE event_type='purchase')>0)
    SELECT a.*,activity_recent_14-activity_previous_14 activity_change,
    (activity_recent_14-activity_previous_14)::DOUBLE/nullif(activity_previous_14,0) activity_relative_change,
    activity_previous_14=0 no_activity_baseline,c.category_view_concentration
    FROM aggregates a LEFT JOIN concentration c USING(user_id)