// Editable presentation generated from the run's immutable metric manifest.
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const mode=process.argv[2]??'full'; if(!['dev','full'].includes(mode))throw Error('Invalid mode');
const runtime=process.env.CODEX_ARTIFACT_RUNTIME??'/Users/nik/.cache/codex-runtimes/codex-primary-runtime/dependencies';
const skill=process.env.CODEX_PRESENTATION_SKILL??'/Users/nik/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations';
const {Presentation,PresentationFile}=await import(pathToFileURL(path.join(runtime,'node/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs')));
process.env.RUNTIME_NODE_MODULES=path.join(runtime,'node/node_modules');
const {resolvePresentationFont,applyPresentationChartFont,finalizePresentation}=await import(pathToFileURL(path.join(skill,'container_tools/artifact_tool_utils.mjs')));
const p=path.join(root,'artifacts',`${mode}-v1`);const read=async name=>JSON.parse(await fs.readFile(path.join(p,name),'utf8'));
const manifest=await read('results_manifest.json');const quality=await read('quality.json');const snapshots=await read('snapshots.json');const audience=await read('audience_summary.json');const trace=(await read('traces/index.json'))[0];const hill=await read('hillstrom/experiment.json');const uplift=await read('hillstrom/uplift.json');const test=await read('test_metrics.json');
const metric=id=>{const m=manifest.metrics.find(x=>x.metric_id===id);if(!m)throw Error(`Missing metric ${id}`);return m.value;};
const pct=x=>(x*100).toFixed(1)+'%';const num=x=>Number(x).toLocaleString('en-US');
const font=resolvePresentationFont();const deck=Presentation.create({slideSize:{width:1280,height:720}});
const out=path.join(p,'slides');const tmp=path.join(p,'slide_build');await fs.mkdir(out,{recursive:true});await fs.mkdir(tmp,{recursive:true});
let n=0;const chartOwners=[];
function textbox(slide,text,x,y,w,h,size=26,color='#173b35',bold=false){const t=slide.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});t.text=text;t.text.style={typeface:font,fontSize:size,bold,color,autoFit:'none'};return t;}
function slide(title,body,notes=''){const s=deck.slides.add();n++;s.background.fill='#fbfcfa';textbox(s,title,64,42,1148,116,42,'#173b35',true);if(body)textbox(s,body,68,172,1110,398,29);textbox(s,`${mode.toUpperCase()} reconstruction / ${n}     ${notes.startsWith('Hillstrom')?'Hillstrom independent randomized email study':'REES46 cosmetics, Oct 2019–Feb 2020'}`,68,651,1110,35,16,'#526a65');s.speakerNotes.textFrame.setText(`${manifest.disclosure}\n${notes}\nSource: artifacts/${mode}-v1/results_manifest.json and accompanying run artifacts. Dataset references: https://www.kaggle.com/datasets/mkechinov/ecommerce-events-history-in-cosmetics-shop ; https://blog.minethatdata.com/2008/03/minethatdata-e-mail-analytics-and-data.html`);return s;}
function chart(s,categories,values,seriesName,caption,{percent=false}={}){const c=s.charts.add('bar',{position:{left:90,top:190,width:1090,height:350},categories,series:[{name:seriesName,values:values.map(x=>Number(x.toFixed(8))),valuesFormatCode:percent?'0.0%':(Math.max(...values)>1?'#,##0':'0.000'),dataLabelOverrides:values.map((v,idx)=>({idx,text:percent?pct(v):(v>1?num(v):v.toFixed(3)),showValue:false,textStyle:{fontSize:18,typeface:font}})),fill:'#167264'}],barOptions:{direction:'column',grouping:'clustered'},hasLegend:false,xAxis:{textStyle:{fontSize:17,typeface:font}},yAxis:{min:0,numberFormatCode:percent?'0.0%':(Math.max(...values)>1?'#,##0':'0.000'),title:{text:seriesName,textStyle:{typeface:font,fontSize:17}}},dataLabels:{showValue:true,position:'outEnd',textStyle:{fontSize:18,typeface:font}}});applyPresentationChartFont(c,{fontFamily:font});textbox(s,caption,75,570,1120,62,21,'#526a65');chartOwners.push(n);}
slide('Customer retention and win-back analytics','A public-data reconstruction for Nikita Thakur\n\nDecision: which previous buyers should enter a prospective win-back test?\n\nThis work does not establish original Macy’s implementation or measured company impact.','Business framing and historical boundary. No outreach has occurred.');
slide('Two datasets answer different questions','REES46 shopping events support forward-looking non-repurchase risk and candidate cohorts.\n\nHillstrom randomized assignments support independent email treatment comparisons.\n\nCustomer identities, predictions and business effects remain separate.','Cosmetics 2019–2020 and Hillstrom 2008. No identity join or effect transport.');
{const s=slide('Five months contain '+num(metric('source_rows'))+' events','', 'Observed counts. Raw multiplicity is retained.');chart(s,quality.monthly_full_source.map(x=>x.file),quality.monthly_full_source.map(x=>x.n),'Original event rows',`${num(quality.analytical_waterfall.identical_excess)} identical excess rows remain visible. Currency and true orders are unverified.`);}
slide('The target looks 28 days into the future','Feature window: [cutoff minus 60 days, cutoff)\nEligible: at least one purchase within that window\nOutcome: any purchase in [cutoff, cutoff plus 28 days)\n\nTrain: 1 Dec 2019   Validation: 30 Dec 2019\nTest: 28 Jan 2020   Latest: 1 Mar 2020\n\nLatest future labels are unknown.','All timestamps UTC. Training labels mature before validation; validation before test. Events at cutoff belong only to outcome.');
{const s=slide('Most eligible buyers do not return within 28 days','','Observed mature cohort proportions; not permanent churn.');chart(s,snapshots.filter(x=>x.label_mature).map(x=>x.split),snapshots.filter(x=>x.label_mature).map(x=>metric('non_repurchase_prevalence_'+x.split)),'Non-repurchase rate','Each cutoff has its own eligible cohort. High prevalence limits what accuracy alone can tell us.',{percent:true});}
{const s=slide('Digital signals improve the purchase-only comparison','','Matched test cohort for both feature sets; lower Brier is better.');chart(s,['Purchase logistic','Combined logistic','Purchase tree','Combined tree'],['logistic_purchase','logistic_combined','tree_purchase','tree_combined'].map(x=>metric(x+'_brier')),'Test Brier score','Both families use the same buyers and time windows. All model choices preceded the final test.');}
{const s=slide('The frozen model ranks risk above the baselines','','Model selected using validation-policy Brier. Test remains an evaluation, not model selection.');chart(s,['Constant','Recency','Combined logistic','Combined tree'],['constant','recency','logistic_combined','tree_combined'].map(x=>metric(x+'_roc_auc')),'Test ROC-AUC',`Selected ${manifest.selected_model}: AUC ${metric(manifest.selected_model+'_roc_auc').toFixed(3)}. Test N=${num(metric('eligible_buyers_test'))}.`);}
slide('One anonymous buyer has a source-reconciled score',`Observed user ${trace.user_id}\n\nPurchase recency: ${trace.manual_reconciliation.purchase_recency.toFixed(2)} days\nPurchasing days in history: ${trace.manual_reconciliation.purchasing_days_60}\nHistorical event-value proxy: ${trace.manual_reconciliation.value_60.toFixed(2)} source units\nPredicted non-repurchase: ${pct(trace.risk)}\nPrimary segment: ${trace.segment}\n\nSource files and row positions remain in the local trace.`,`Actual source trace. Future label ${trace.retrospective_non_repurchase} is retrospective only and never an audience field.`);
{const s=slide(num(metric('candidate_count_latest_unlabeled'))+' customers enter the local candidate list','','Local analytical audience. Consent/contactability unknown. No sending authorization.');const seg=audience.at(-1).segments;chart(s,Object.keys(seg).map(x=>x.replaceAll('_','\n')),Object.values(seg),'Eligible customers by primary segment','Recent buyers are suppressed. Capacity and risk ranking define proposed candidates, not incremental profit.');}
slide('Campaign economics require explicit assumptions','Incremental contribution per contact:\n\nδ × basket value × margin\n− (p₀ + δ) × redemption × incentive cost\n− contact cost\n\nIncentives also cost money on natural converters.\nThe app leaves all assumptions blank until supplied.','ASSUMPTION_SCENARIO. No observed untreated counterfactual inferred from risk. No achieved ROI claimed.');
slide('A future holdout can test whether contact changes purchases','Proposed arms: no contact, useful content, incentive\nStable customer assignment and campaign-overlap controls\nPrimary outcome: 28-day observed repurchase\nIntention-to-treat denominators and adjusted comparisons\n\nPower needs an assumed control rate and meaningful effect.\nThe existing assignment export is a dry run only.','Prospective cosmetics protocol. Verify permission/contactability and power before activation. Bonferroni planning for two treatment-control comparisons.');
{const s=slide('The independent email trial shows observed conversion differences','','Hillstrom independent randomized email experiment, 64,000 assigned customers.');chart(s,hill.arm_summary.map(x=>x.arm),hill.arm_summary.map(x=>metric('hillstrom_'+x.arm+'_conversion_rate')),'14-day conversion rate','All assigned customers enter the denominator. Creative labels identify merchandise, not customer gender.',{percent:true});}
slide('Uplift targeting remains uncertain in the held-out sample',`Independent Hillstrom engagement target: website visit\n\nTest Qini: ${metric('hillstrom_visit_qini').toFixed(4)}\n95% bootstrap interval: ${uplift.qini_ci95.map(x=>x.toFixed(4)).join(' to ')}\n\nThe interval includes zero. These results do not establish a reliable heterogeneous targeting advantage.\n\nVisit uplift is separate from purchase retention.`,`Hillstrom independent study. T-learner fixed before test. Qini uses scikit-uplift and 200 row bootstrap samples. IPW policy values remain estimates.`);
slide('The next decision is a controlled campaign test','Use the frozen ranking to support candidate review.\nVerify contactability, consent and campaign overlap.\nCollect delivery, cost, margin and guardrail outcomes.\nRun a prespecified randomized experiment.\n\nRead the learning guide and trace before presenting results.\nKeep reconstruction findings separate from employment claims.','Recommendation from measured full run. No revenue saved, campaign deployment or original-company impact is inferred.');
const candidate=path.join(tmp,'candidate.pptx');await(await PresentationFile.exportPptx(deck)).save(candidate);
let final=path.join(out,'retention_winback.pptx');try{await fs.access(final);final=path.join(out,`retention_winback_${Date.now()}.pptx`);}catch{}
await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:final,pythonExecutable:path.join(runtime,'python/bin/python3'),integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],explicitTotalSlideCount:14,requiredNativeChartOwnerSlides:chartOwners,materializeLiteralChartWorkbooks:true,fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:path.join(tmp,`validation-${Date.now()}.json`)});
for(let i=0;i<deck.slides.items.length;i++){const slide=deck.slides.items[i];const preview=await deck.export({slide,format:'png',scale:1});await fs.writeFile(path.join(tmp,`slide-${i+1}.png`),new Uint8Array(await preview.arrayBuffer()));}
await fs.writeFile(path.join(out,'presentation_provenance.json'),JSON.stringify({pptx:final,manifest:path.join(p,'results_manifest.json'),slides:14,nativeChartOwnerSlides:chartOwners,font},null,2));
console.log(final);
